misc: xilinx-ai-engine: Fix UAPI header to use __u32 instead of u32
UAPI headers must use __u32 instead of u32 as the latter is a kernel
internal type not available to userspace.

Without this fix, the header test fails:

  ./usr/include/linux/xlnx-ai-engine.h:398:9: error: unknown type name 'u32'
    398 |         u32 bd[18];

Fixes: 576fd1b02e69 ("xilinx-ai-engine: add SHIM DMA dmabuf BD config support to io_uring cmd")
Reported-by: Bhanu Teja Yadav Perugu <byadavpe@amd.com>
Signed-off-by: Michal Simek <michal.simek@amd.com>
Acked-by: Sankarji Gopalakrishnan <sankarji@amd.com>
Message-ID: <c53e13e43886cb4f5bb0dbb71a41b44e1f44cb36.1775574311.git.michal.simek@amd.com>